### ISSUE TITLE
Using variable in tag of NBT results in error

### ISSUE THREAD

**Issue by Til0mi** [jaylawl/jNBT#2]
This works
```
on right click holding flint and steel:
	set {_value} to tag "asd" of held item's nbt
	broadcast "%{_value}%"
```

but this results in the error below
```
on right click holding flint and steel:
	set {_tool} to held item
	set {_value} to tag "asd" of {_tool}'s nbt
	broadcast "%{_value}%"
```
```
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! [Skript] Severe Error:
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Something went horribly wrong with Skript.
[11:58:54 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:58:54 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:58:54 ERROR]: #!#! Here is full list of them:
[11:58:54 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon ExtrasSK skUtilities (https://tim740.github.io/) skript-yaml SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) MundoSK (https://forums.skunity.com/resources/mundosk.69/)
[11:58:54 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:58:54 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:58:54 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:58:54 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:58:54 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:58:54 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[11:58:54 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Stack trace:
[11:58:54 ERROR]: #!#! java.lang.NullPointerException
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:327)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.g(SourceFile:331)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.l(SourceFile:292)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.b(SourceFile:308)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.f(SourceFile:177)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:34)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.parse(SourceFile:29)
[11:58:54 ERROR]: #!#! at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:38)
[11:58:54 ERROR]: #!#! at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:15)
[11:58:54 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[11:58:54 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:275)
[11:58:54 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[11:58:54 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[11:58:54 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:58:54 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[11:58:54 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[11:58:54 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[11:58:54 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[11:58:54 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:58:54 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
[11:58:54 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
[11:58:54 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236)
[11:58:54 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203)
[11:58:54 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1030)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[11:58:54 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:58:54 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[11:58:54 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[11:58:54 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Version Information:
[11:58:54 ERROR]: #!#! Skript: 2.2-dev37c (latest)
[11:58:54 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:58:54 ERROR]: #!#! Minecraft: 1.12.2
[11:58:54 ERROR]: #!#! Java: 1.8.0_171 (OpenJDK 64-Bit Server VM 25.171-b11)
[11:58:54 ERROR]: #!#! OS: Linux amd64 4.4.0-116-generic
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Server platform: Paper
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Current node: null
[11:58:54 ERROR]: #!#! Current item: set {_value}(as java.lang.Object) to Tag of NBT
[11:58:54 ERROR]: #!#! Current trigger: right click holding flint and steel (click holding [[itemtype:flint_and_steel]]) (test.sk, line 11)
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Thread: Server thread
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! Language: english
[11:58:54 ERROR]: #!#! Link parse mode: STRICT
[11:58:54 ERROR]: #!#!
[11:58:54 ERROR]: #!#! End of Error.
[11:58:54 ERROR]: #!#!
```

Also if the item doesn't contain the tag, it results in this error
```
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! [Skript] Severe Error:
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Something went horribly wrong with Skript.
[12:11:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:11:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:11:39 ERROR]: #!#! Here is full list of them:
[12:11:39 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon ExtrasSK skUtilities (https://tim740.github.io/) skript-yaml SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) MundoSK (https://forums.skunity.com/resources/mundosk.69/)
[12:11:39 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:11:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:11:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:11:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:11:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:11:39 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[12:11:39 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Stack trace:
[12:11:39 ERROR]: #!#! java.lang.NullPointerException
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:327)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.g(SourceFile:331)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.l(SourceFile:292)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.b(SourceFile:308)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.f(SourceFile:177)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:34)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MojangsonParser.parse(SourceFile:29)
[12:11:39 ERROR]: #!#! at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:38)
[12:11:39 ERROR]: #!#! at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:15)
[12:11:39 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[12:11:39 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:275)
[12:11:39 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:11:39 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:11:39 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:11:39 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[12:11:39 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[12:11:39 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[12:11:39 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:11:39 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:11:39 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
[12:11:39 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
[12:11:39 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236)
[12:11:39 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203)
[12:11:39 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1030)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:11:39 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:11:39 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[12:11:39 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[12:11:39 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Version Information:
[12:11:39 ERROR]: #!#! Skript: 2.2-dev37c (latest)
[12:11:39 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
[12:11:39 ERROR]: #!#! Minecraft: 1.12.2
[12:11:39 ERROR]: #!#! Java: 1.8.0_171 (OpenJDK 64-Bit Server VM 25.171-b11)
[12:11:39 ERROR]: #!#! OS: Linux amd64 4.4.0-116-generic
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Server platform: Paper
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Current node: null
[12:11:39 ERROR]: #!#! Current item: set {_value}(as java.lang.Object) to Tag of NBT
[12:11:39 ERROR]: #!#! Current trigger: right click holding flint and steel (click holding [[itemtype:flint_and_steel]]) (test.sk, line 11)
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Thread: Server thread
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! Language: english
[12:11:39 ERROR]: #!#! Link parse mode: STRICT
[12:11:39 ERROR]: #!#!
[12:11:39 ERROR]: #!#! End of Error.
[12:11:39 ERROR]: #!#!
```

**Comment by jaylawl** [comment]
oh boy i should've done more testing

**Comment by jaylawl** [comment]
For the first error, please specify `item-nbt`, instead of just `nbt`.
```
on right click holding flint and steel:
	set {_tool} to held item
	set {_value} to tag "asd" of {_tool}'s item-nbt
	broadcast "%{_value}%"
```

**Comment by jaylawl** [comment]
The second error has been fixed in 0.3.1

**Comment by Til0mi** [comment]
Awesome, thank you!

**Comment by ghost** [comment]
Hi everybody!

I get the same error like @Til0mi when the item does not contain the specified tag (with 0.3.1).

```
[17:36:57 ERROR]: #!#! Stack trace:
[17:36:57 ERROR]: #!#! java.lang.NullPointerException
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:327)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.g(SourceFile:331)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.l(SourceFile:292)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.b(SourceFile:308)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.f(SourceFile:177)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:34)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MojangsonParser.parse(SourceFile:29)
[17:36:57 ERROR]: #!#!     at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:38)
[17:36:57 ERROR]: #!#!     at de.jaylawl.jnbt.elements.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:15)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:268)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[17:36:57 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[17:36:57 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:36:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[17:36:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[17:36:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[17:36:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:36:57 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:36:57 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:36:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:36:57 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:36:57 ERROR]: #!#!
[17:36:57 ERROR]: #!#! Version Information:
[17:36:57 ERROR]: #!#!   Skript: 2.2-dev36
[17:36:57 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:36:57 ERROR]: #!#!   Minecraft: 1.12.2
[17:36:57 ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[17:36:57 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:36:57 ERROR]: #!#!
[17:36:57 ERROR]: #!#! Server platform: Spigot
[17:36:57 ERROR]: #!#!
[17:36:57 ERROR]: #!#! Current node: null
[17:36:57 ERROR]: #!#! Current item: set {_object.type}(as java.lang.Object) to Tag of NBT
[17:36:57 ERROR]: #!#! Current trigger: leftclick (leftclick) (09_Enchants.sk, line 1155)
```

Thank you for help! <3

**Comment by jaylawl** [comment]
But, but... i fixed this. Are you using the latest download? What's your code?

**Comment by ghost** [comment]
I use the latest download yes, I tried 2 times :P
```
on leftclick:
	set {_object.type} to tag "object" of nbt of player's tool
```

I tried this too
```
on leftclick:
	set {_object.type} to tag "object" of item-nbt of player's tool
```

**Comment by Til0mi** [comment]
Yeah me too, still getting the same error with Goethus's code on version 0.3.1

**Comment by jaylawl** [comment]
I can only reproduce this if there isn't any NBT on the item. does the check out with you guys?

**Comment by jaylawl** [comment]
Anyway i fixed it in 0.3.2, please let me know if it should happen again. Sorry for the lack of quality, it's my first java plugin and i'm trying my best :dancer:

**Comment by ghost** [comment]
Perfect! It works for me :)
